### ISSUE TITLE
*.pfs.(number) folder

### ISSUE THREAD

**Issue by apkpeaks** [nextgal/pfs_upk#6]
Hello sir thank you so much for creating this amazing tool
Can you add function to extract filename.pfs.(number) to folder named filename.pfs.(number)? Tool only extract the all file into the root.pfs folder and when packing it merges all into 1 file, it doesn't split the files like the original

**Comment by ryank231231** [comment]
the tool currently only strip the "extension" part, and take the basename of the archive as the output path.

that's why all the files are extracted into the same folder.

so we have two ways to do split folders:
- rename the archive first and extract, then rename it back
- change the way to generate the outputPath

for the second way, we also have 3 different methods:
-  /extracted/root.pfs.001/
-  /root.pfs_001/
-  /root.pfs.001_extracted/

**Comment by ryank231231** [comment]
fixed in v1.2.0 release.
